---
title: "lab1"
author: "zhexuan"
date: "`r Sys.Date()`"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE, echo=False}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(forcats)
library(MASS)    # for polr
```

## Task 4

**Load Data**

```{r load, echo=False}
setwd("E:/KTH/Y1S1S2/statistic/lab1")
data3 <- read.csv("Data_T3.csv")
data4A <- read.csv("Data_T4A.csv")
data4B <- read.csv("Data_T4B.csv")

str(data4A);table(data4A$Response, useNA="ifany")
str(data4B);table(data4B$SPMSQ, useNA="ifany")
```

```{r arrangement}

spmsq_levels <- c("Normal", "Mild", "Moderate", "Severe")

data4A <- data4A %>%
  mutate(
    Treatment = factor(Treatment, levels = c(0,1,2,3),
                       labels = c("Control","Low","Medium","High")),
    Response = factor(Response, levels = spmsq_levels, ordered = TRUE)
  )

data4B <- data4B %>%
  mutate(
    SPMSQ = factor(SPMSQ, levels = spmsq_levels, ordered = TRUE)
  )

```

**Q1**

Visualization of the four study arms:

```{r Q1 visualization}

# calculate the frequencies and percentage
spmsq_tab <- data4A %>%
  group_by(Treatment, Response) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  group_by(Treatment) %>%
  mutate(freq = n / sum(n))

# stacked percentage bar chart 
ggplot(spmsq_tab, aes(x = Treatment, y = freq, fill = Response)) +
  geom_bar(stat = "identity", position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  labs(y = "Percentage", title = "SPMSQ distribution by Treatment (stacked %)",
       caption = "Responses: Normal -> Severe") +
  theme_minimal()

```

**Q2**

Visualizations of SPMSQ given the biomarker in Task 3:

```{r Q2 visualization}
# merge data3 and data4A
merged_34A <- left_join(data4A,data3[,c("ID","NFL")],by="ID")

# box plot
ggplot(merged_34A, aes(x = Response, y = NFL)) +
  geom_boxplot() +
  geom_jitter(width = 0.15, alpha = 0.6) +
  labs(title = "NfL by SPMSQ response (overall)",
       y = "NfL (pg/mL)") +
  theme_minimal()

# NFL normal or not
hist(data3$NFL, breaks=20, main="Histogram of NfL", xlab="NfL")
shapiro.test(data3$NFL)

# NFL isn't normal -> log-transform
merged_34A$logNFL <- log(merged_34A$NFL)
ggplot(merged_34A, aes(x = Response, y = logNFL)) +
  geom_boxplot() + facet_wrap(~Treatment) +
  labs(title = "log(NfL) by SPMSQ and Treatment", y = "log(NfL)") +
  theme_minimal()
```
```{r polr}
merged_34A$Response <- factor(merged_34A$Response, levels = spmsq_levels, ordered = TRUE)

# logistic (proportional odds model)
ord_model <- polr(Response ~ logNFL + Treatment, data = merged_34A, Hess = TRUE)
summary(ord_model)

# p-value of the coefficient
ctable <- coef(summary(ord_model))
pvals <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
cbind(ctable, "p value" = pvals)
```

**Q3**

```{r Q3 visualization}

# ID OCC1 OCC2
data4B_wide <- data4B %>%
  dplyr::select(ID, OCC, SPMSQ) %>%
  pivot_wider(names_from = OCC, values_from = SPMSQ, names_prefix = "OCC")

# transfer table
trans_table <- table(data4B_wide$OCC1, data4B_wide$OCC2)
trans_table

# transfer heat map
trans_df <- as.data.frame(as.table(trans_table))
colnames(trans_df) <- c("OCC1","OCC2","Count")
ggplot(trans_df, aes(x = OCC1, y = OCC2, fill = Count)) +
  geom_tile() +
  geom_text(aes(label = Count), color = "white") +
  labs(title = "Transition matrix: SPMSQ OCC1 -> OCC2") +
  theme_minimal()

# Individual connection diagram
level_map <- setNames(1:4, spmsq_levels)
data4B_wide <- data4B_wide %>%
  mutate(occ1_num = level_map[as.character(OCC1)],
         occ2_num = level_map[as.character(OCC2)])

data4B_long <- data4B_wide %>%
  dplyr::select(ID, occ1_num, occ2_num) %>%
  pivot_longer(cols = starts_with("occ"), names_to = "OCC", values_to = "Score") %>%
  mutate(OCC = ifelse(OCC=="occ1_num", "OCC1", "OCC2"))

ggplot(data4B_long, aes(x = OCC, y = Score, group = ID)) +
  geom_line(alpha = 0.6) +
  geom_point() +
  scale_y_continuous(breaks = 1:4, labels = spmsq_levels) +
  labs(title = "Individual SPMSQ changes between OCC1 and OCC2",
       y = "SPMSQ (ordered)") +
  theme_minimal()

# alluvial
library(ggalluvial)
alluv_df <- data4B_wide %>% mutate(OCC1 = as.character(OCC1), OCC2 = as.character(OCC2))
ggplot(alluv_df, aes(axis1 = OCC1, axis2 = OCC2, y = 1)) +
   geom_alluvium(aes(fill = OCC1)) +
   geom_stratum() + geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
   scale_x_discrete(labels=c("OCC1","OCC2")) +
   ggtitle("Alluvial of SPMSQ transitions")

```

```{r}
library(irr)
# Prepare data: two columns of factor levels
kappa_data <- data4B_wide %>% dplyr::select(OCC1, OCC2)
# kappa2
kappa2_res <- kappa2(as.data.frame(kappa_data), weight = "squared")
kappa2_res

# Wilcoxon signed-rank 
wilcox_res <- wilcox.test(data4B_wide$occ1_num, data4B_wide$occ2_num, paired = TRUE)
wilcox_res
```

